- hosts: localhost
  vars:
    apppath: "{{ansible_env.PWD}}/Hoge"
    appname: Hoge
    database: mysql
    ruby_version: 2.1.5
  roles:
    - new
    - gitignore
    - gem
    - ruby_version
    - bundle_install
    - db
    - git_commit
