- name: check folder already exists
  stat: path=./{{ appname }}
  register: p

- name: do nothing when folder already exists
  debug: msg="app already exists"
  when: p.stat.isdir is defined and p.stat.isdir

- name: make new app
  shell: rails new {{ appname }} --skip-bundle -d {{ database }} -T
  when: p.stat.isdir is not defined
